# Release charm's libraries if they have changed
name: Release Libraries

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/user_verification_service/**"

jobs:
  release-lib:
    name: Release any bumped library
    uses: canonical/identity-team/.github/workflows/charm-libs-release.yaml@732520bcf8f04f777f44d1c3677e7a89f7ce9ab6 # v1.11.0
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}