# Release charm's libraries if they have changed
name: Release Libraries

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/user_verification_service/**"

jobs:
  release-lib:
    name: Release any bumped library
    uses: canonical/identity-team/.github/workflows/charm-libs-release.yaml@5830f3e6723de07cb5b7ccb6c84031d8b2964c62 # v1.11.4
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}