# Release charm's libraries if they have changed
name: Release Libraries

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/user_verification_service/**"

jobs:
  release-lib:
    name: Release any bumped library
    uses: canonical/identity-team/.github/workflows/charm-libs-release.yaml@59d4d2782bcb8fc2deea2aa08442e4c8603f2689 # v1.11.2
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}